name: PC4262_project
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - jupyterlab
  - nbdime
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - xarray>=2025.3.1
  - matplotlib
  - ultraplot
  - seaborn
  - ipykernel
  - pymc>=5
  - py6s
  - pip:
      - nbstripout

